/**
 * Image pipeline. Run with `npm run media` after adding or replacing a source
 * photograph — NOT on every build.
 *
 * Sources live in assets/photos and are never served. This emits graded,
 * resized AVIF + WebP derivatives into public/media, plus a typed manifest, and
 * BOTH are committed. That keeps sharp off the deploy critical path entirely,
 * so any host can build the site with no native dependencies — which is what
 * makes "host-agnostic" true rather than aspirational.
 *
 * A sidecar JSON beside a photo can declare named crops:
 *   { "crops": { "nozzle": { "left": 0.42, "top": 0.31, "width": 0.2, "height": 0.2 } } }
 * Each crop becomes its own manifest entry with its own width ladder.
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { GRADE_VERSION, applyGrade } from "./lib/grade.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE_DIR = path.join(ROOT, "assets/photos");
const OUT_DIR = path.join(ROOT, "public/media");
const MANIFEST = path.join(ROOT, "src/generated/media.ts");

const WIDTHS = [320, 480, 640, 768, 1024, 1280, 1600];
/** 24px wide, inlined as base64. Big enough to blur to 48px, ~500 bytes. */
const LQIP_WIDTH = 24;

async function readSidecar(slug) {
  const file = path.join(SOURCE_DIR, `${slug}.json`);
  if (!existsSync(file)) return {};
  return JSON.parse(await readFile(file, "utf8"));
}

/** One rendered variant: a whole photo, or a named crop of it. */
async function renderVariant({ slug, buffer, crop }) {
  const probe = sharp(buffer).rotate();
  const { width: srcWidth, height: srcHeight } = await probe.metadata();

  let region = null;
  if (crop) {
    region = {
      left: Math.round(crop.left * srcWidth),
      top: Math.round(crop.top * srcHeight),
      width: Math.round(crop.width * srcWidth),
      height: Math.round(crop.height * srcHeight),
    };
  }

  const finalWidth = region ? region.width : srcWidth;
  const finalHeight = region ? region.height : srcHeight;

  // Never upscale. A crop of a 1536px export is small, and inventing pixels
  // to fill a hero is exactly the kind of thing that reads as cheap.
  const widths = WIDTHS.filter((w) => w <= finalWidth);
  if (!widths.length) widths.push(finalWidth);

  const base = () => {
    let p = sharp(buffer).rotate();
    if (region) p = p.extract(region);
    return applyGrade(p);
  };

  for (const width of widths) {
    const resized = () => base().resize({ width, withoutEnlargement: true });
    await resized().avif({ quality: 52, effort: 6 }).toFile(path.join(OUT_DIR, `${slug}-${width}.avif`));
    await resized().webp({ quality: 78 }).toFile(path.join(OUT_DIR, `${slug}-${width}.webp`));
  }

  const lqipBuffer = await base()
    .resize({ width: LQIP_WIDTH })
    .jpeg({ quality: 40 })
    .toBuffer();

  return {
    width: finalWidth,
    height: finalHeight,
    widths,
    lqip: `data:image/jpeg;base64,${lqipBuffer.toString("base64")}`,
  };
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(path.dirname(MANIFEST), { recursive: true });

  const files = (await readdir(SOURCE_DIR)).filter((f) => /\.(jpe?g|png)$/i.test(f));
  if (!files.length) {
    console.error(`No source images in ${SOURCE_DIR}`);
    process.exit(1);
  }

  const manifest = {};

  for (const file of files.sort()) {
    const slug = file.replace(/\.[^.]+$/, "");
    const buffer = await readFile(path.join(SOURCE_DIR, file));
    const sidecar = await readSidecar(slug);

    const hash = createHash("sha256")
      .update(buffer)
      .update(String(GRADE_VERSION))
      .update(JSON.stringify(sidecar.crops ?? {}))
      .digest("hex")
      .slice(0, 12);

    manifest[slug] = { ...(await renderVariant({ slug, buffer })), hash };
    process.stdout.write(`  ${slug}\n`);

    for (const [name, crop] of Object.entries(sidecar.crops ?? {})) {
      const cropSlug = `${slug}-${name}`;
      manifest[cropSlug] = { ...(await renderVariant({ slug: cropSlug, buffer, crop })), hash };
      process.stdout.write(`  ${cropSlug} (crop)\n`);
    }
  }

  const body = `// GENERATED by scripts/media.mjs — do not edit by hand.
// Run \`npm run media\` after adding or replacing a source photograph.

export type MediaEntry = {
  width: number;
  height: number;
  widths: number[];
  lqip: string;
  hash: string;
};

export const media = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, MediaEntry>;

export type MediaSlug = keyof typeof media;
`;

  await writeFile(MANIFEST, body);
  console.log(`\n${Object.keys(manifest).length} entries → ${path.relative(ROOT, MANIFEST)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
